version: '3'

services:
  app:
    build: .
    command: npm start
    container_name: nodejs-api
    ports:
      - '9000:9000'
    volumes:
      - .:/usr/app
    depends_on:
      - db

  db:
    image: 'mongo'
    container_name: mongo-db
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - '27017:27017'

